export const SEED = 88172645;

export const COMPANY_NAME = "Solstice Technologies, Inc.";
export const COMPANY_DOMAIN = "solsticetech.com";

export const FIRST_NAMES = [
  "Amara",
  "Jonas",
  "Priya",
  "Mateo",
  "Elena",
  "Kwame",
  "Freya",
  "Diego",
  "Naomi",
  "Lucas",
  "Sofia",
  "Ravi",
  "Ingrid",
  "Tomas",
  "Chidinma",
  "Oliver",
  "Yuki",
  "Aisha",
  "Marcus",
  "Nadia",
  "Felix",
  "Leila",
  "Hassan",
  "Clara",
  "Dmitri",
  "Zainab",
  "Andres",
  "Mei",
  "Sean",
  "Fatima",
  "Bjorn",
  "Camila",
  "Rohan",
  "Ines",
  "Kenji",
  "Adaeze",
  "Milo",
  "Sasha",
  "Owen",
  "Layla",
  "Viktor",
  "Nia",
  "Gabriel",
  "Renata",
  "Amir",
  "Josephine",
  "Nikolai",
  "Thandiwe",
  "Pedro",
  "Isla",
  "Kai",
  "Alina",
  "Tariq",
  "Greta",
  "Emeka",
  "Rosa",
  "Anders",
  "Mariam",
  "Julian",
  "Wren",
  "Dev",
  "Solveig",
  "Cyrus",
  "Bianca",
  "Noor",
  "Callum",
  "Ximena",
  "Theo",
  "Adanna",
] as const;

export const LAST_NAMES = [
  "Whitfield",
  "Ferreira",
  "Chandrasekaran",
  "Okafor",
  "Bergstrom",
  "Nakamura",
  "Alvarado",
  "Kowalski",
  "Mensah",
  "Delacroix",
  "Novak",
  "Petrova",
  "Osei",
  "Lindqvist",
  "Farrow",
  "Beaumont",
  "Adeyemi",
  "Castellano",
  "Voss",
  "Hallström",
  "Odhiambo",
  "Marchetti",
  "Kimura",
  "Reyes",
  "Van der Berg",
  "Solheim",
  "Achebe",
  "Baptiste",
  "Ionescu",
  "Nazarov",
  "Whitaker",
  "Coelho",
  "Sundaram",
  "Larsen",
  "Mwangi",
  "Rousseau",
  "Takahashi",
  "Fontaine",
  "Braithwaite",
  "Dubois",
  "Okonkwo",
  "Pemberton",
  "Silveira",
  "Andersson",
  "Nakashima",
  "Herrera",
  "Kaczmarek",
  "Abara",
  "Lindgren",
  "Sinclair",
  "Moretti",
  "Yamada",
  "Ashworth",
  "Bello",
  "Carvalho",
  "Eriksen",
  "Nwosu",
  "Beckett",
  "Ivanov",
  "Okafor-Lee",
  "Hargrove",
  "Duarte",
  "Skov",
  "Adebayo",
  "Marlowe",
  "Petronio",
  "Osborne",
  "Vance",
] as const;

export const LOCATIONS = [
  "New York, NY",
  "San Francisco, CA",
  "Austin, TX",
  "Chicago, IL",
  "London, UK",
  "Berlin, Germany",
  "Toronto, Canada",
  "Singapore",
  "Remote",
] as const;

export const DEPARTMENT_DEFINITIONS = [
  {
    id: "dept-executive",
    name: "Executive Leadership",
    code: "EXE",
    description: "Sets company strategy and oversees all functional leadership teams.",
    targetHeadcount: 9,
    budget: 4200000,
    reportsTo: null as string | null,
  },
  {
    id: "dept-engineering",
    name: "Engineering",
    code: "ENG",
    description: "Builds and operates the core product, platform and infrastructure.",
    targetHeadcount: 32,
    budget: 9800000,
    reportsTo: "Chief Technology Officer",
  },
  {
    id: "dept-product",
    name: "Product Management",
    code: "PM",
    description: "Defines product strategy, roadmap and cross-functional delivery.",
    targetHeadcount: 11,
    budget: 2400000,
    reportsTo: "Chief Product Officer",
  },
  {
    id: "dept-design",
    name: "Design",
    code: "DES",
    description: "Owns product design, research and the design system.",
    targetHeadcount: 9,
    budget: 1900000,
    reportsTo: "Chief Product Officer",
  },
  {
    id: "dept-data",
    name: "Data & Analytics",
    code: "DATA",
    description: "Delivers analytics, experimentation and data infrastructure.",
    targetHeadcount: 10,
    budget: 2600000,
    reportsTo: "Chief Technology Officer",
  },
  {
    id: "dept-it",
    name: "IT & Security",
    code: "IT",
    description: "Runs internal systems, corporate IT and security operations.",
    targetHeadcount: 9,
    budget: 2100000,
    reportsTo: "Chief Technology Officer",
  },
  {
    id: "dept-sales",
    name: "Sales",
    code: "SAL",
    description: "Drives new business acquisition and revenue growth.",
    targetHeadcount: 19,
    budget: 5200000,
    reportsTo: "Chief Revenue Officer",
  },
  {
    id: "dept-marketing",
    name: "Marketing",
    code: "MKT",
    description: "Builds brand awareness, demand generation and lifecycle marketing.",
    targetHeadcount: 13,
    budget: 4100000,
    reportsTo: "Chief Revenue Officer",
  },
  {
    id: "dept-customer-success",
    name: "Customer Success",
    code: "CS",
    description: "Drives adoption, retention and expansion across the customer base.",
    targetHeadcount: 13,
    budget: 2300000,
    reportsTo: "Chief Revenue Officer",
  },
  {
    id: "dept-customer-support",
    name: "Customer Support",
    code: "SUP",
    description: "Provides frontline technical support across every region.",
    targetHeadcount: 15,
    budget: 2000000,
    reportsTo: "Chief Revenue Officer",
  },
  {
    id: "dept-finance",
    name: "Finance",
    code: "FIN",
    description: "Manages financial planning, treasury and investor relations.",
    targetHeadcount: 8,
    budget: 1800000,
    reportsTo: "Chief Financial Officer",
  },
  {
    id: "dept-accounting",
    name: "Accounting",
    code: "ACC",
    description: "Owns the books, payroll operations and financial controls.",
    targetHeadcount: 7,
    budget: 1400000,
    reportsTo: "Chief Financial Officer",
  },
  {
    id: "dept-hr",
    name: "Human Resources",
    code: "HR",
    description: "Leads people programs, employee relations and HR operations.",
    targetHeadcount: 7,
    budget: 1500000,
    reportsTo: "Chief People Officer",
  },
  {
    id: "dept-talent",
    name: "Talent Acquisition",
    code: "TA",
    description: "Runs full-cycle recruiting across every open requisition.",
    targetHeadcount: 7,
    budget: 1600000,
    reportsTo: "Chief People Officer",
  },
  {
    id: "dept-legal",
    name: "Legal & Compliance",
    code: "LEG",
    description: "Manages contracts, regulatory compliance and corporate governance.",
    targetHeadcount: 5,
    budget: 1700000,
    reportsTo: "Chief Executive Officer",
  },
  {
    id: "dept-operations",
    name: "Operations & Facilities",
    code: "OPS",
    description: "Keeps offices, vendors and internal operations running smoothly.",
    targetHeadcount: 7,
    budget: 1300000,
    reportsTo: "Chief Operating Officer",
  },
] as const;

export type DepartmentId = (typeof DEPARTMENT_DEFINITIONS)[number]["id"];

interface TitleDef {
  title: string;
  level: "Senior" | "Mid" | "Junior";
}

export const DEPARTMENT_IC_TITLES: Record<string, TitleDef[]> = {
  "dept-engineering": [
    { title: "Staff Software Engineer", level: "Senior" },
    { title: "Senior Software Engineer", level: "Senior" },
    { title: "Software Engineer II", level: "Mid" },
    { title: "Software Engineer I", level: "Junior" },
    { title: "Site Reliability Engineer", level: "Mid" },
    { title: "QA Engineer", level: "Mid" },
    { title: "DevOps Engineer", level: "Mid" },
  ],
  "dept-product": [
    { title: "Group Product Manager", level: "Senior" },
    { title: "Senior Product Manager", level: "Senior" },
    { title: "Product Manager", level: "Mid" },
    { title: "Associate Product Manager", level: "Junior" },
  ],
  "dept-design": [
    { title: "Principal Product Designer", level: "Senior" },
    { title: "Senior Product Designer", level: "Senior" },
    { title: "Product Designer", level: "Mid" },
    { title: "UX Researcher", level: "Mid" },
    { title: "Junior Product Designer", level: "Junior" },
  ],
  "dept-data": [
    { title: "Senior Data Scientist", level: "Senior" },
    { title: "Data Scientist", level: "Mid" },
    { title: "Senior Data Analyst", level: "Senior" },
    { title: "Data Analyst", level: "Mid" },
    { title: "Analytics Engineer", level: "Mid" },
  ],
  "dept-it": [
    { title: "Security Engineer", level: "Senior" },
    { title: "Systems Administrator", level: "Mid" },
    { title: "IT Support Specialist", level: "Junior" },
    { title: "Network Engineer", level: "Mid" },
  ],
  "dept-sales": [
    { title: "Senior Account Executive", level: "Senior" },
    { title: "Account Executive", level: "Mid" },
    { title: "Sales Development Representative", level: "Junior" },
    { title: "Solutions Consultant", level: "Mid" },
  ],
  "dept-marketing": [
    { title: "Senior Marketing Manager", level: "Senior" },
    { title: "Content Marketing Manager", level: "Mid" },
    { title: "Growth Marketing Manager", level: "Mid" },
    { title: "Brand Designer", level: "Mid" },
    { title: "Marketing Specialist", level: "Junior" },
  ],
  "dept-customer-success": [
    { title: "Senior Customer Success Manager", level: "Senior" },
    { title: "Customer Success Manager", level: "Mid" },
    { title: "Onboarding Specialist", level: "Junior" },
  ],
  "dept-customer-support": [
    { title: "Senior Support Engineer", level: "Senior" },
    { title: "Support Engineer", level: "Mid" },
    { title: "Support Associate", level: "Junior" },
  ],
  "dept-finance": [
    { title: "Senior Financial Analyst", level: "Senior" },
    { title: "FP&A Analyst", level: "Mid" },
    { title: "Financial Analyst", level: "Junior" },
  ],
  "dept-accounting": [
    { title: "Senior Accountant", level: "Senior" },
    { title: "Staff Accountant", level: "Mid" },
    { title: "Accounts Payable Specialist", level: "Junior" },
  ],
  "dept-hr": [
    { title: "Senior HR Business Partner", level: "Senior" },
    { title: "HR Business Partner", level: "Mid" },
    { title: "HR Generalist", level: "Junior" },
    { title: "People Operations Coordinator", level: "Junior" },
  ],
  "dept-talent": [
    { title: "Senior Technical Recruiter", level: "Senior" },
    { title: "Recruiter", level: "Mid" },
    { title: "Recruiting Coordinator", level: "Junior" },
  ],
  "dept-legal": [
    { title: "Corporate Counsel", level: "Senior" },
    { title: "Compliance Analyst", level: "Mid" },
    { title: "Paralegal", level: "Junior" },
  ],
  "dept-operations": [
    { title: "Facilities Manager", level: "Senior" },
    { title: "Operations Coordinator", level: "Mid" },
    { title: "Office Manager", level: "Junior" },
  ],
};

export const DEPARTMENT_HEAD_TITLES: Record<string, string> = {
  "dept-engineering": "VP of Engineering",
  "dept-product": "VP of Product",
  "dept-design": "Head of Design",
  "dept-data": "Head of Data & Analytics",
  "dept-it": "Head of IT & Security",
  "dept-sales": "VP of Sales",
  "dept-marketing": "VP of Marketing",
  "dept-customer-success": "Head of Customer Success",
  "dept-customer-support": "Head of Customer Support",
  "dept-finance": "VP of Finance",
  "dept-accounting": "Controller",
  "dept-hr": "Head of Human Resources",
  "dept-talent": "Head of Talent Acquisition",
  "dept-legal": "General Counsel",
  "dept-operations": "Head of Operations",
};

export const DEPARTMENT_MANAGER_TITLES: Record<string, string> = {
  "dept-engineering": "Engineering Manager",
  "dept-product": "Product Lead",
  "dept-design": "Design Lead",
  "dept-data": "Analytics Manager",
  "dept-it": "IT Manager",
  "dept-sales": "Sales Manager",
  "dept-marketing": "Marketing Manager",
  "dept-customer-success": "Customer Success Lead",
  "dept-customer-support": "Support Team Lead",
  "dept-finance": "FP&A Manager",
  "dept-accounting": "Accounting Manager",
  "dept-hr": "HR Manager",
  "dept-talent": "Recruiting Manager",
  "dept-legal": "Compliance Manager",
  "dept-operations": "Operations Manager",
};

export const EXECUTIVE_TEAM = [
  { title: "Chief Executive Officer", reportsTo: null as string | null },
  { title: "Chief Operating Officer", reportsTo: "Chief Executive Officer" },
  { title: "Chief Financial Officer", reportsTo: "Chief Executive Officer" },
  { title: "Chief Technology Officer", reportsTo: "Chief Executive Officer" },
  { title: "Chief Product Officer", reportsTo: "Chief Executive Officer" },
  { title: "Chief Revenue Officer", reportsTo: "Chief Executive Officer" },
  { title: "Chief People Officer", reportsTo: "Chief Executive Officer" },
] as const;

export const SKILLS_POOL = [
  "TypeScript",
  "React",
  "Node.js",
  "Python",
  "SQL",
  "Kubernetes",
  "AWS",
  "Product Strategy",
  "Roadmapping",
  "User Research",
  "Figma",
  "Design Systems",
  "Data Modeling",
  "A/B Testing",
  "Salesforce",
  "Negotiation",
  "Account Management",
  "SEO",
  "Content Strategy",
  "Paid Media",
  "Customer Onboarding",
  "Zendesk",
  "Financial Modeling",
  "Forecasting",
  "GAAP",
  "Payroll",
  "Employee Relations",
  "HRIS",
  "Sourcing",
  "Applicant Tracking",
  "Contract Law",
  "Risk Management",
  "Vendor Management",
  "Project Management",
  "Public Speaking",
  "Leadership",
  "Mentoring",
  "Agile",
  "Security Compliance",
  "Network Administration",
] as const;

export const COMPANIES = [
  "Nimbus Retail Co.",
  "Bluewave Analytics",
  "Foundry Systems",
  "Cascade Robotics",
  "Lumen Financial",
  "Orbital Health",
  "Meridian Logistics",
  "Vertex Media Group",
  "Anchor Cloud",
  "Solace Biotech",
  "Ironclad Manufacturing",
  "Beacon Insurance",
  "Driftwood Studios",
  "Pinnacle Freight",
  "Northstar Energy",
  "Clearwater Systems",
  "Amber Retail Group",
  "Fernbank Labs",
  "Silverline Telecom",
  "Kestrel Aerospace",
] as const;

export const UNIVERSITIES = [
  "State University",
  "Lakeside Institute of Technology",
  "Northbridge University",
  "Cascadia College",
  "Harrow Polytechnic",
  "Bellmont University",
  "Fairview State College",
  "Ashford Institute",
  "Westgate University",
  "Elmsworth College",
] as const;

export const DEGREES = [
  "B.S. Computer Science",
  "B.A. Business Administration",
  "B.S. Marketing",
  "M.B.A.",
  "B.S. Finance",
  "B.A. Communications",
  "B.S. Data Science",
  "B.A. Human Resources",
  "B.S. Information Systems",
  "M.S. Computer Science",
] as const;

export const APPLICATION_SOURCES = [
  "Careers Site",
  "LinkedIn",
  "Employee Referral",
  "Job Board",
  "Recruiting Agency",
  "University Fair",
] as const;

export const LEAVE_REASONS: Record<string, string[]> = {
  Annual: ["Family vacation", "Personal travel", "Time off to recharge", "Visiting family abroad"],
  Sick: ["Flu symptoms", "Medical appointment", "Recovering from minor surgery", "Migraine"],
  Personal: ["Family matter", "Moving apartments", "Personal errands", "Home repairs"],
  Parental: ["Welcoming a new child", "Parental bonding leave"],
  Unpaid: ["Extended personal travel", "Caring for a family member", "Sabbatical"],
};

export const GOAL_TEMPLATES: Record<string, string[]> = {
  "dept-engineering": [
    "Ship v2 of the platform API",
    "Reduce production incident rate by 30%",
    "Migrate core services to the new infrastructure",
    "Improve deployment frequency",
    "Cut average page load time",
    "Achieve 90% automated test coverage",
  ],
  "dept-product": [
    "Launch self-serve onboarding flow",
    "Define FY27 product roadmap",
    "Increase feature adoption rate",
    "Reduce time-to-value for new customers",
  ],
  "dept-design": [
    "Complete design system v3 rollout",
    "Improve accessibility compliance to AA",
    "Run 12 user research sessions this quarter",
  ],
  "dept-data": [
    "Build the executive analytics dashboard",
    "Stand up the new data warehouse pipeline",
    "Improve forecasting model accuracy",
  ],
  "dept-it": ["Complete SOC 2 audit readiness", "Roll out zero-trust network access", "Reduce ticket backlog by 40%"],
  "dept-sales": [
    "Close $1.2M in new ARR",
    "Expand pipeline in the enterprise segment",
    "Improve win rate on competitive deals",
    "Ramp 3 new account executives",
  ],
  "dept-marketing": [
    "Grow qualified pipeline from campaigns",
    "Launch the FY27 brand refresh",
    "Increase organic traffic by 25%",
  ],
  "dept-customer-success": [
    "Improve net revenue retention",
    "Reduce churn in the mid-market segment",
    "Launch the customer health scoring model",
  ],
  "dept-customer-support": [
    "Reduce average first response time",
    "Improve CSAT to 95%",
    "Launch the self-service help center",
  ],
  "dept-finance": ["Complete FY27 annual budget", "Improve forecast accuracy", "Automate the monthly close process"],
  "dept-accounting": ["Close the books within 3 business days", "Complete the annual audit with zero findings"],
  "dept-hr": ["Improve employee engagement score", "Launch the manager development program"],
  "dept-talent": [
    "Reduce average time-to-hire",
    "Improve offer acceptance rate",
    "Build the university recruiting pipeline",
  ],
  "dept-legal": ["Complete data privacy compliance review", "Standardize the vendor contract template library"],
  "dept-operations": ["Complete the new office buildout", "Reduce vendor spend by 10%"],
  "dept-executive": ["Deliver FY27 strategic plan", "Improve cross-functional alignment on OKRs"],
};

export const COURSE_CATALOG: Omit<import("./types").Course, "id">[] = [
  {
    title: "Leadership Foundations",
    category: "Leadership",
    level: "Beginner",
    durationHours: 6,
    instructor: "Renata Silveira",
    format: "Instructor-led",
    description: "Core people-management skills for new and aspiring managers.",
  },
  {
    title: "Advanced Negotiation Tactics",
    category: "Sales",
    level: "Advanced",
    durationHours: 4,
    instructor: "Marcus Whitaker",
    format: "Workshop",
    description: "Practical frameworks for negotiating complex enterprise deals.",
  },
  {
    title: "Secure Coding Practices",
    category: "Engineering",
    level: "Intermediate",
    durationHours: 8,
    instructor: "Nadia Petrova",
    format: "Self-paced",
    description: "Identify and remediate the most common application security risks.",
  },
  {
    title: "Data Storytelling",
    category: "Data & Analytics",
    level: "Intermediate",
    durationHours: 5,
    instructor: "Kenji Nakamura",
    format: "Self-paced",
    description: "Turn raw analysis into a narrative stakeholders act on.",
  },
  {
    title: "Inclusive Hiring Practices",
    category: "HR",
    level: "Beginner",
    durationHours: 3,
    instructor: "Aisha Mensah",
    format: "Self-paced",
    description: "Reduce bias across sourcing, interviewing and offer decisions.",
  },
  {
    title: "Financial Modeling Essentials",
    category: "Finance",
    level: "Beginner",
    durationHours: 6,
    instructor: "Felix Kowalski",
    format: "Self-paced",
    description: "Build and interpret core financial models used in planning.",
  },
  {
    title: "Design Systems in Practice",
    category: "Design",
    level: "Intermediate",
    durationHours: 5,
    instructor: "Ines Fontaine",
    format: "Workshop",
    description: "Scale a design system across a growing product surface.",
  },
  {
    title: "Customer Success Playbooks",
    category: "Customer Success",
    level: "Beginner",
    durationHours: 4,
    instructor: "Chidinma Okafor",
    format: "Self-paced",
    description: "Repeatable playbooks for onboarding, adoption and renewal.",
  },
  {
    title: "Effective Cross-Functional Communication",
    category: "Professional Skills",
    level: "Beginner",
    durationHours: 3,
    instructor: "Bjorn Solheim",
    format: "Instructor-led",
    description: "Communicate clearly across engineering, product and go-to-market teams.",
  },
  {
    title: "Cloud Infrastructure Fundamentals",
    category: "Engineering",
    level: "Beginner",
    durationHours: 7,
    instructor: "Diego Alvarado",
    format: "Self-paced",
    description: "Core concepts for provisioning and operating cloud infrastructure.",
  },
  {
    title: "Workplace Compliance & Ethics",
    category: "Compliance",
    level: "Beginner",
    durationHours: 2,
    instructor: "Zainab Achebe",
    format: "Self-paced",
    description: "Annual refresher on workplace conduct and compliance obligations.",
  },
  {
    title: "Advanced Product Analytics",
    category: "Product",
    level: "Advanced",
    durationHours: 6,
    instructor: "Priya Chandrasekaran",
    format: "Workshop",
    description: "Instrument and interpret product usage to guide roadmap decisions.",
  },
  {
    title: "Public Speaking & Executive Presence",
    category: "Professional Skills",
    level: "Intermediate",
    durationHours: 4,
    instructor: "Sofia Herrera",
    format: "Instructor-led",
    description: "Present with confidence to leadership, customers and large audiences.",
  },
  {
    title: "Diversity, Equity & Inclusion in Practice",
    category: "HR",
    level: "Beginner",
    durationHours: 3,
    instructor: "Thandiwe Osei",
    format: "Self-paced",
    description: "Build inclusive habits into everyday team decisions.",
  },
];

export const BENEFIT_PLAN_DEFINITIONS: Omit<import("./types").BenefitPlan, "id" | "enrolledCount">[] = [
  {
    name: "Premium PPO Health Plan",
    category: "Health",
    description: "Comprehensive medical, dental and vision coverage with a national provider network.",
    eligibility: "All full-time employees",
    monthlyCost: 640,
    participationRate: 0.86,
    status: "Active",
  },
  {
    name: "High-Deductible Health Plan + HSA",
    category: "Health",
    description: "Lower-premium medical plan paired with a company HSA contribution.",
    eligibility: "All full-time employees",
    monthlyCost: 410,
    participationRate: 0.31,
    status: "Active",
  },
  {
    name: "401(k) Retirement Plan",
    category: "Retirement",
    description: "Company matches 100% of the first 4% of contributions, fully vested from day one.",
    eligibility: "All employees, 90 days tenure",
    monthlyCost: 0,
    participationRate: 0.78,
    status: "Active",
  },
  {
    name: "Life & AD&D Insurance",
    category: "Insurance",
    description: "Company-paid life insurance at 2x annual salary.",
    eligibility: "All full-time employees",
    monthlyCost: 0,
    participationRate: 0.97,
    status: "Active",
  },
  {
    name: "Short & Long-Term Disability",
    category: "Insurance",
    description: "Income protection coverage for extended illness or injury.",
    eligibility: "All full-time employees",
    monthlyCost: 0,
    participationRate: 0.91,
    status: "Active",
  },
  {
    name: "Commuter & Transit Allowance",
    category: "Allowances",
    description: "Pre-tax monthly allowance for public transit or parking.",
    eligibility: "All employees, office-based",
    monthlyCost: 150,
    participationRate: 0.42,
    status: "Active",
  },
  {
    name: "Remote Work Stipend",
    category: "Allowances",
    description: "Quarterly stipend for home office equipment and internet.",
    eligibility: "All remote employees",
    monthlyCost: 75,
    participationRate: 0.58,
    status: "Active",
  },
  {
    name: "Wellness & Fitness Reimbursement",
    category: "Wellness",
    description: "Monthly reimbursement for gym memberships and fitness classes.",
    eligibility: "All employees",
    monthlyCost: 60,
    participationRate: 0.47,
    status: "Active",
  },
  {
    name: "Mental Health & EAP",
    category: "Wellness",
    description: "Confidential counseling sessions and an employee assistance program.",
    eligibility: "All employees and dependents",
    monthlyCost: 0,
    participationRate: 0.36,
    status: "Active",
  },
  {
    name: "Paid Parental Leave",
    category: "Wellness",
    description: "16 weeks of fully paid leave for new parents.",
    eligibility: "All employees, 6 months tenure",
    monthlyCost: 0,
    participationRate: 0.12,
    status: "Active",
  },
  {
    name: "Global Travel Insurance",
    category: "Insurance",
    description: "Coverage for employees traveling internationally on company business.",
    eligibility: "Employees who travel for work",
    monthlyCost: 0,
    participationRate: 0.22,
    status: "Upcoming",
  },
];

export const HOLIDAYS_2026: { title: string; date: string }[] = [
  { title: "Labor Day", date: "2026-09-07" },
  { title: "Indigenous Peoples' Day", date: "2026-10-12" },
  { title: "Veterans Day", date: "2026-11-11" },
  { title: "Thanksgiving Day", date: "2026-11-26" },
  { title: "Winter Break Begins", date: "2026-12-24" },
];
